[Icon Theme]
Name=N.I.B.
Comment=
Inherits=Adwaita,breeze,hicolor

Example=directory-x-normal

#Directory list
Directories=apps/scalable,places/scalable,mimes/scalable,

[apps/scalable]
Size=48
Context=Applications
Type=Scalable
Minsize=8
Maxsize=512

[places/scalable]
Size=16
Context=Places
Type=Scalable
Minsize=8
Maxsize=512

[mimes/scalable]
Size=48
Context=MimeTypes
Type=Scalable
MinSize=8
MaxSize=512

